# Generated by Django 2.2.6 on 2019-10-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkerId', models.IntegerField(default=1)),
                ('FirstName', models.CharField(max_length=20)),
                ('EmailId', models.CharField(max_length=50)),
                ('PhNo', models.IntegerField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
